declare const m: {
    a: (x: number) => number;
    ac: (x: number) => number;
    acs: (x: number) => number;
    as: (x: number) => number;
    ass: (x: number) => number;
    at: (x: number) => number;
    ats: (x: number) => number;
    at2: (y: number, x: number) => number;
    cbrt: (x: number) => number;
    ce: (x: number) => number;
    clz: (x: number) => number;
    C: (x: number) => number;
    csh: (x: number) => number;
    E: (x: number) => number;
    expm1: (x: number) => number;
    F: (x: number) => number;
    fr: (x: number) => number;
    H: (...values: number[]) => number;
    imul: (x: number, y: number) => number;
    L: (x: number) => number;
    lp1: (x: number) => number;
    l10: (x: number) => number;
    l2: (x: number) => number;
    max: (...values: number[]) => number;
    min: (...values: number[]) => number;
    pow: (x: number, y: number) => number;
    R: () => number;
    ro: (x: number) => number;
    s: (x: number) => number;
    S: (x: number) => number;
    sh: (x: number) => number;
    Q: (x: number) => number;
    T: (x: number) => number;
    th: (x: number) => number;
    tr: (x: number) => number;
    M: Math;
};
export default m;
