declare class ScriptCanvas extends HTMLCanvasElement {
    static get observedAttributes(): string[];
    _scriptInterval: any;
    _context: any;
    _paused: boolean;
    _active: boolean;
    _script: any;
    _fps: number;
    _scriptFunction: any;
    _lastUpdate: number;
    _startTime: number;
    delta: any;
    coef: any;
    etn: any;
    GR: any;
    GRV: any;
    stack: any;
    stackAverage: any;
    total: number;
    prev: number;
    c: this;
    r: any;
    x: any;
    y: any;
    pals: any;
    palVals: any;
    di: number;
    raf: any;
    totalAverage: any;
    range: any;
    overlayVisible: boolean;
    constructor();
    connectedCallback(): void;
    disconnectedCallback(): void;
    attributeChangedCallback(name: string, _oldValue: any, newValue: boolean): void;
    startScriptRunner(): void;
    setScript(s: any): void;
    setupVariables(): void;
    setupOverlayVariables(): void;
    setupContext(): void;
    pause(): void;
    resume(): void;
    stop(): void;
    start(): void;
    createContext(): any;
    _scriptRunner(): void;
    getPauseAmount(): number;
    drawOverlay(): void;
}
export default ScriptCanvas;
